# Generated by Django 6.0.5 on 2026-06-09 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Reporting Person', 'Reporting Person'), ('HR', 'HR'), ('Founder', 'Founder')], default='Student', max_length=20)),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('branch_department', models.CharField(max_length=100, verbose_name='Branch/Dept')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('reporting_person', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Staff', 'Reporting Person', 'HR', 'Founder']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='profiles.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
