# Generated by Django 6.0.5 on 2026-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Reporting Person', 'Reporting Person'), ('HR', 'HR'), ('Founder', 'Founder')], default='Student', max_length=50),
        ),
    ]
