# Generated by Django 6.0.5 on 2026-06-09 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('holiday_type', models.CharField(choices=[('Government', 'Government Holiday'), ('Semester', 'Semester Holiday'), ('Institution', 'Institution Closure'), ('Exam_Break', 'Exam Preparation Break')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2026)),
                ('sick_total', models.IntegerField(default=12)),
                ('sick_used', models.IntegerField(default=0)),
                ('casual_total', models.IntegerField(default=10)),
                ('casual_used', models.IntegerField(default=0)),
                ('emergency_total', models.IntegerField(default=3)),
                ('emergency_used', models.IntegerField(default=0)),
                ('exam_total', models.IntegerField(default=5)),
                ('exam_used', models.IntegerField(default=0)),
                ('other_total', models.IntegerField(default=0)),
                ('other_used', models.IntegerField(default=0)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student')], max_length=10)),
                ('department', models.CharField(blank=True, default='Computer Science', max_length=100, null=True)),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick leave'), ('Casual Leave', 'Casual Leave '), ('Emergency Leave', 'Emergency Leave '), ('Exam Leave', 'Exam Leave '), ('Other', 'Other / Custom')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.IntegerField()),
                ('reason', models.TextField()),
                ('doc_path', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('current_stage', models.CharField(choices=[('Trainer_Review', 'Awaiting Trainer/Staff Review'), ('Reporting_Review', 'Awaiting Reporting Person Review'), ('HR_Review', 'Awaiting HR Review'), ('Founder_Review', 'Awaiting Founder Review')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Fully Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reporting_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_role', models.CharField(max_length=50)),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_approvals', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest')),
            ],
        ),
    ]
