# Generated by Django 6.0.5 on 2026-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapproval',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applicant_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(max_length=300),
        ),
    ]
