# Generated by Django 6.0.5 on 2026-06-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaveapproval_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolidayCalendar',
        ),
    ]
